# Register
POST http://localhost:3000/v1/users
Content-Type: application/json

{
    "name":"johndoe",
    "email":"example@example.com",
    "password":"123456",
    "confirmPassword":"123456"
}

# Login
###
POST http://localhost:3000/v1/users/login
Content-Type: application/json

{
    "email":"07tav2@gmsail.com",
    "password":"123456"
}

###
POST http://localhost:3000/v1/users/login
Content-Type: application/json

{
    "email":"07tav2akbar@gmail.com",
    "password":"123456"
}

# Get Data Users
###
GET http://localhost:3000/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2YTkyYzk2LTdkOTktNDI5Mi1iYTg4LWYxNTUzMjgwNTllMyIsIm5hbWUiOiJNb2NoYW1hZCBTeWFocnVsIEFrYmFyIiwiZW1haWwiOiIwN3RhdjJha2JhckBnbWFpbC5jb20iLCJpYXQiOjE2ODU3MDUxMDIsImV4cCI6MTY4NTcwNjAwMn0.aky-KVWHtTyIE1ma09JIe3Buos9Uw6CBekGaPgMZquI

# Get Data User By Id
###
GET http://localhost:3000/v1/users/487d0de1-9578-452b-adda-e9744ba1940a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ4N2QwZGUxLTk1NzgtNDUyYi1hZGRhLWU5NzQ0YmExOTQwYSIsIm5hbWUiOiJNb2NoYW1hZCBTeWFocnVsIEFrYmFyIiwiZW1haWwiOiIwN3RhdjJAZ21zYWlsLmNvbSIsImlhdCI6MTY4NTcwNzIyOSwiZXhwIjoxNjg1NzA4MTI5fQ.srCaprYs0iBhFRnALXpcZ_9nOK5Hcf1SmC-Wc0UpzKQ

# Get New Access Token
###
GET http://localhost:3000/v1/users/token

# Logout
###
DELETE http://localhost:3000/v1/users/logout